---
- hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Gather facts about an Ethernet Network V247
      oneview_ethernet_network_facts:
        name: V247
        hostname: "{{ ov_hostname }}"
        username: "{{ ov_username }}"
        password: "{{ ov_password}}"
        api_version: "{{ ov_api_version}}"
      delegate_to: localhost

    - debug: var=ethernet_networks
