---
- hosts: localhost
  vars:
    ov_hostname: "{{ lookup('env', 'ONEVIEWSDK_IP') }}"
    ov_username: "{{ lookup('env', 'ONEVIEWSDK_USERNAME') }}"
    ov_password: "{{ lookup('env', 'ONEVIEWSDK_PASSWORD') }}"
    ov_api_version: "{{ lookup('env', 'ONEVIEWSDK_API_VERSION') }}"
  tasks:
  - name: Read from settings.csv
    read_csv:
      path: settings.csv
      delimiter: ","
    register: settings
    delegate_to: localhost
  - name: Iterate through settings and create ESXi servers
    include: ov_ESXi_server_tasks.yml
    with_items: "{{ settings.list }}"