---
- hosts: localhost
  any_errors_fatal: true
  vars:
    server_profile_template: GSE-SPT
    server_name: VMHESX101
    os_deployment_plan: ESxi 6.7-2
    ip_address: 10.188.188.50
    domainName: synergy.local
    dns1: 10.188.0.2
    dns2: 10.188.0.3
    gateway: 10.188.188.1
    netmask: 255.255.255.0
    connectionid: 1
    serverhardware: MXQ71906VL, bay 1
    esxi_password: HP!nvent123
    vcenter_hostname: 10.188.29.15
    vcenter_username: Administrator@vsphere.local
    vcenter_password: HP!nvent123
    datacenter_name: GSE-Houston
    network_set_name: GSE-NS
    cluster_name: GSE-Cluster
    vcenter_switch_name: GSE-DSWITCH
    index: 1
    vlanid: 188
    vmnic: vmnic1
    ov_hostname: "10.188.0.180"
    ov_username: "v188usradmin"
    ov_password: "HP!nvent123"
    ov_api_version: 800
  tasks:
  - debug: msg="{{ov_api_version}}"
  - name: Gather facts about all Server Profiles
    oneview_server_profile_facts:
      hostname: "{{ ov_hostname }}"
      username: "{{ ov_username }}"
      password: "{{ ov_password }}"
      api_version: "{{ ov_api_version}}"
    delegate_to: localhost
  - debug: msg="{{server_profiles | map(attribute='name') | list }}"
  - debug: var=server_profiles
