---
- hosts: localhost
  any_errors_fatal: true
  tasks:
  - debug: msg="{{ov_api_version}}"
  - name: Gather facts about server profile by name
    oneview_server_profile_facts:
      hostname: "{{ ov_hostname }}"
      username: "{{ ov_username }}"
      password: "{{ ov_password }}"
      api_version: "{{ ov_api_version}}"
      name: test
    delegate_to: localhost
  - debug: var=server_profiles
