export ONEVIEWSDK_IP="10.188.0.210"
export ONEVIEWSDK_USERNAME='v210usradmin'
export ONEVIEWSDK_PASSWORD='HP!nvent123'
export ONEVIEWSDK_API_VERSION=800
export ONEVIEWSDK_AUTH_LOGIN_DOMAIN=''
export VCENTER_HOSTNAME=""
export VCENTER_USERNAME=""
export VCENTER_PASSWORD=""